Fix helm charts with numeric versions
Chart versions can be numeric, but kubernetes chokes on numeric label
values, resulting in errors like

Error: release my-nats failed: Secret in version "v1" cannot be handled
as a Secret: v1.Secret: Type: ObjectMeta: v1.ObjectMeta: Namespace:
Name: Labels: ReadString: expects " or n, but found 1, error found in
 #10 byte of ...|version":1,"helm.sh/|..., bigger context
...|s.io/name":"my-nats","app.kubernetes.io/version":1,"helm.sh/chart":"my-nats-1","skiff-role-name":"re|...

To fix this the version label value is always quoted.